// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/audit': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/audit.get').default>>>>
    }
    '/api/admin/content/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/content/[id].delete').default>>>>
    }
    '/api/admin/reports': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/reports.get').default>>>>
    }
    '/api/admin/reports/:id/resolve': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/reports/[id]/resolve.post').default>>>>
    }
    '/api/admin/settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/settings.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/settings.put').default>>>>
    }
    '/api/admin/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stats.get').default>>>>
    }
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users.get').default>>>>
    }
    '/api/admin/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].delete').default>>>>
    }
    '/api/admin/users/:id/role': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id]/role.put').default>>>>
    }
    '/api/admin/users/:id/status': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id]/status.put').default>>>>
    }
    '/api/content/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id].put').default>>>>
    }
    '/api/content/:id/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id]/products.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id]/products.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id]/products.put').default>>>>
    }
    '/api/content/:id/products/:productId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id]/products/[productId].delete').default>>>>
    }
    '/api/content/:id/publish': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id]/publish.post').default>>>>
    }
    '/api/content/:id/report': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id]/report.post').default>>>>
    }
    '/api/content/:id/versions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id]/versions.get').default>>>>
    }
    '/api/content/:id/view': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id]/view.post').default>>>>
    }
    '/api/content/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[slug].get').default>>>>
    }
    '/api/content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/index.post').default>>>>
    }
    '/api/contests/:slug': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contests/[slug].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contests/[slug].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contests/[slug].put').default>>>>
    }
    '/api/contests/:slug/entries': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contests/[slug]/entries.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contests/[slug]/entries.post').default>>>>
    }
    '/api/contests/:slug/judge': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contests/[slug]/judge.post').default>>>>
    }
    '/api/contests/:slug/transition': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contests/[slug]/transition.post').default>>>>
    }
    '/api/contests': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contests/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contests/index.post').default>>>>
    }
    '/api/docs/:siteSlug': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug].put').default>>>>
    }
    '/api/docs/:siteSlug/nav': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug]/nav.get').default>>>>
    }
    '/api/docs/:siteSlug/pages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug]/pages.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug]/pages.post').default>>>>
    }
    '/api/docs/:siteSlug/pages/:pageId': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug]/pages/[pageId].put').default>>>>
    }
    '/api/docs/:siteSlug/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug]/search.get').default>>>>
    }
    '/api/docs/:siteSlug/versions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug]/versions.post').default>>>>
    }
    '/api/docs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/index.post').default>>>>
    }
    '/api/files/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/files/[id].delete').default>>>>
    }
    '/api/files/mine': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/files/mine.get').default>>>>
    }
    '/api/files/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/files/upload.post').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/hubs/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug].get').default>>>>
    }
    '/api/hubs/:slug/bans': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/bans.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/bans.post').default>>>>
    }
    '/api/hubs/:slug/bans/:userId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/bans/[userId].delete').default>>>>
    }
    '/api/hubs/:slug/feed.xml': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/feed.xml.get').default>>>>
    }
    '/api/hubs/:slug/gallery': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/gallery.get').default>>>>
    }
    '/api/hubs/:slug/invites': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/invites.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/invites.post').default>>>>
    }
    '/api/hubs/:slug/join': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/join.post').default>>>>
    }
    '/api/hubs/:slug/leave': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/leave.post').default>>>>
    }
    '/api/hubs/:slug/members': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/members.get').default>>>>
    }
    '/api/hubs/:slug/members/:userId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/members/[userId].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/members/[userId].put').default>>>>
    }
    '/api/hubs/:slug/posts/:postId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/posts/[postId].delete').default>>>>
    }
    '/api/hubs/:slug/posts/:postId/replies': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/posts/[postId]/replies.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/posts/[postId]/replies.post').default>>>>
    }
    '/api/hubs/:slug/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/posts/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/posts/index.post').default>>>>
    }
    '/api/hubs/:slug/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/products.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/products.post').default>>>>
    }
    '/api/hubs/:slug/share': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/[slug]/share.post').default>>>>
    }
    '/api/hubs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hubs/index.post').default>>>>
    }
    '/api/learn/:slug': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug].put').default>>>>
    }
    '/api/learn/:slug/:lessonSlug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/[lessonSlug].get').default>>>>
    }
    '/api/learn/:slug/:lessonSlug/complete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/[lessonSlug]/complete.post').default>>>>
    }
    '/api/learn/:slug/enroll': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/enroll.post').default>>>>
    }
    '/api/learn/:slug/lessons': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/lessons.post').default>>>>
    }
    '/api/learn/:slug/modules': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/modules.post').default>>>>
    }
    '/api/learn/:slug/modules/:moduleId': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/modules/[moduleId].put').default>>>>
    }
    '/api/learn/:slug/publish': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/publish.post').default>>>>
    }
    '/api/learn/:slug/unenroll': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/unenroll.post').default>>>>
    }
    '/api/learn/certificates': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/certificates.get').default>>>>
    }
    '/api/learn/enrollments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/enrollments.get').default>>>>
    }
    '/api/learn': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/index.post').default>>>>
    }
    '/api/messages/:conversationId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/[conversationId].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/[conversationId].post').default>>>>
    }
    '/api/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/index.post').default>>>>
    }
    '/api/notifications/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/[id].delete').default>>>>
    }
    '/api/notifications/count': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/count.get').default>>>>
    }
    '/api/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/index.get').default>>>>
    }
    '/api/notifications/read': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/read.post').default>>>>
    }
    '/api/notifications/stream': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/stream.get').default>>>>
    }
    '/api/products/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].put').default>>>>
    }
    '/api/products/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[slug].get').default>>>>
    }
    '/api/products/:slug/content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[slug]/content.get').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.get').default>>>>
    }
    '/api/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile.put').default>>>>
    }
    '/api/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search.get').default>>>>
    }
    '/api/social/bookmark': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/bookmark.post').default>>>>
    }
    '/api/social/bookmarks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/bookmarks.get').default>>>>
    }
    '/api/social/comments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/comments.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/comments.post').default>>>>
    }
    '/api/social/comments/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/comments/[id].delete').default>>>>
    }
    '/api/social/like': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/like.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/like.post').default>>>>
    }
    '/api/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats.get').default>>>>
    }
    '/api/users/:username': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[username].get').default>>>>
    }
    '/api/users/:username/content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[username]/content.get').default>>>>
    }
    '/api/users/:username/feed.xml': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[username]/feed.xml.get').default>>>>
    }
    '/api/users/:username/follow': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[username]/follow.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[username]/follow.post').default>>>>
    }
    '/api/users/:username/followers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[username]/followers.get').default>>>>
    }
    '/api/users/:username/following': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[username]/following.get').default>>>>
    }
    '/api/videos/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/videos/[id].get').default>>>>
    }
    '/api/videos/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/videos/categories.get').default>>>>
    }
    '/api/videos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/videos/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/videos/index.post').default>>>>
    }
    '/.well-known/nodeinfo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/.well-known/nodeinfo').default>>>>
    }
    '/.well-known/webfinger': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/.well-known/webfinger').default>>>>
    }
    '/feed.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/feed.xml').default>>>>
    }
    '/inbox': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/inbox').default>>>>
    }
    '/nodeinfo/2.1': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/nodeinfo/2.1').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/robots.txt').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap.xml').default>>>>
    }
    '/users/:username': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/users/[username]').default>>>>
    }
    '/users/:username/followers': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/users/[username]/followers').default>>>>
    }
    '/users/:username/following': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/users/[username]/following').default>>>>
    }
    '/users/:username/inbox': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/users/[username]/inbox').default>>>>
    }
    '/users/:username/outbox': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/users/[username]/outbox').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@3.21.1_db0@0.3.4_drizzle-orm@0.38.4_kysely@0.28.11_pg@8.20.0___drizz_07dfe389c2ad4c703151522bdf7a8e92/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}